resources:         
  containers:
  - container: smartHotel 
    connection: myDockerRegistry
    image: smartHotelApp 

stages:
- stage: rootBuild
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building!
- stage: rootTest
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!