resources:         
  containers:
  - container: petStore      
    type: ACR  
    azureSubscription: ContosoARMConnection
    resourceGroup: ContosoGroup
    registry: petStoreRegistry
    repository: myPets
    trigger: 
      tags:
        include: 
        - production*

stages:
- stage: rootBuild
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building!
- stage: rootTest
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!